### PR TITLE
New SNP  vignette

### PR DESCRIPTION
**Pull request by smanel**
Fst- AMOVA

### CODE REVIEW

**Comment by zkamvar** [comment]
This is a good start!

There are a few things that I feel need to be addressed (check them off as they are filled):

- [ ] the organism should be identified (which Pinus species?)
- [ ] formatting errors need to be fixed (header information, link to the data, heading inconruency)
- [ ] make sure code can be run in non-interactive mode
- [ ] reduce number of permutations for tests (on my computer, these take a lot of time to run)
- [ ] further reduce the data (perhaps only select 10 random loci)
- [ ] show how the user can use the output of the functions

Once these are done, it will be a great addition for SNP data!

**Comment by smanel** [comment]
Thank you for the back.
To make changes, I need to work on the file on my computer (local) and to submitt the vignette again?
What do you mean in an non-interactive mode: the user is going to dowload all the files on his own computer?

**Comment by zkamvar** [comment]
> To make changes, I need to work on the file on my computer (local) and to submitt the vignette again?

For basic changes, you can work on the document on github by [clicking this link](https://github.com/NESCent/popgenInfo/edit/Manel_vignette/use/VignetteDifferentiationSNPbisGithub.Rmd)

You can test it on your computer by following these steps:

1. pull the branch to your computer
2. make changes
3. commit those changes
4. pull again to make sure that you have received everyone's changes
5. push back to the repository 

Note that step 4 is necessary here because we all have access to your branch and can make changes.

> What do you mean in an non-interactive mode: the user is going to dowload all the files on his own computer?

Non-interactive mode means that the workflow will be able to run without the user needing to type anything. For example, [these lines](https://github.com/NESCent/popgenInfo/blame/d9a8b73b83bac1576d063f007adbc29046a985ad/use/VignetteDifferentiationSNPbisGithub.Rmd#L130-L140) contain functions that require the user to input values (number of PCs and number of DAs). When the vignette is run on the server, it will not be able to generate the web page because it will expect user input. Currently, you have `eval = FALSE`, which prevents the code from being run, but you cannot show any results this way. Though, this may not be a bad thing since choosing the number of PCs and DAs is a necessarily exploratory step and this will encourage the user to run the code themselves.

**Comment by hlapp** [comment]
> You can test it on your computer by following these steps:
> 
> 1. pull the branch to your computer

@smanel you will have this branch already on your computer if you are still using the same laptop as you did as when you submitted the pull request. If you work on a fresh clone on some other computer, the branch will have come down to the machine as part of the clone; then simply use `git checkout Manel_vignette` to check out and switch to that branch.

> 2. make changes
> 3. commit those changes
> 4. pull again to make sure that you have received everyone's changes

This is correct as a general best practice. (Also, the Github GUI client will show you if there are un-synchronized changes.) For this one, for now I think we can all just agree that you are the only one editing unless you'd like someone else to help. To do so, just post a comment here as to what you'd like assistance with.

> 5. push back to the repository

FYI, for any pull request you submit, you can keep adding commits (and thus changes) by simply adding to and then pushing commits to the same branch.

**Comment by smanel** [comment]
I will probably work directly on my computer to make more tests with R. That means that I need to download again the vignette. 
If I keep  the same name: it will erase the previous version? Sould I change the name?

**Comment by hlapp** [comment]
On 3/24/15, 9:57 AM, Manel wrote:
>
> I will probably work directly on my computer to make more tests with
> R. That means that I need to download again the vignette.
>

Only if you work on a different computer, and then you clone the whole
repository.

> If I keep the same name: it will erase the previous version? Sould I
> change the name?
>

No, please do not change the name. Not erasing previous versions is the
whole point of version control, and everything in this repository is
under version control. Save a version by committing. You do not need to
push ("synchronize") every time you commit.

**Comment by zkamvar** [comment]
@smanel, do you have github for windows? If you don't, you can download it here: https://windows.github.com/. It might make things a little easier. Additionally, here's a link that describes how to work on github: https://guides.github.com/introduction/flow/index.html. (For reference, we are on step 4)

**Comment by hlapp** [comment]
@smanel I fixed your two vignettes. The HTML rendering will expect UTF8 encoding from all documents. If you don't have any diacritical characters in a document, this won't matter. But if there are any diacritics, the document needs to be saved in UTF8 encoding. I don't know which editor you use, so can't say how to accomplish it there. If saving documents in UTF8 is an issue, we need to look into ways to convert them to UTF8 at build time.

Before you continue editing, please make sure you synchronize and pull down the changes from Github. Also, it would make managing your changes easier if each document were in a separate pull request. I hadn't realized that two were in this one. (You can create a new pull request by switching back to `master` branch, then create a new branch.)

**Comment by zkamvar** [comment]
I have made stylistic edits to `VignetteDifferentiationSNPbisGithub.Rmd`, mainly placing spaces around binary operators (`=` and `<-`) and after commas. I also took out all the `eval = FALSE` flags so that the examples would run.

As a stylistic note, I would suggest to place code comments that are longer than a line inside the main text as it makes them easier to read.

**Comment by smanel** [comment]
In both vignette, the link to import the dataset does not go into  the good folder: it goes into the user folder? 
Mydata <- read.table("../data/Master_Pinus_data_genotype.txt", header = T).

**Comment by zkamvar** [comment]
If I understand correctly, you want the user to see this:

```r
Mydata <- read.table("Master_Pinus_data_genotype.txt", header = T)
```

If so, you will need two R chunks. One that actually reads the data in, but doesn't show the code (`echo = FALSE`) and one that the user sees, but does nothing (`eval = FALSE`):

    ```{r, read_data, echo = FALSE}
    Mydata <- read.table("../data/Master_Pinus_data_genotype.txt", header = T)
    ```
    ```{r, user_data, eval = FALSE}
    Mydata <- read.table("Master_Pinus_data_genotype.txt", header = T)
    ```

**Comment by zkamvar** [comment]
I have made some small changes to the vignettes regarding spelling and style.

One more suggestion before we merge this vignette: Change long comments in the code to text.

For example, in VignetteStartSNP.Rmd, 

this:
****

```r
#To convert MydataR to genind object (adegent): Mydata2 needs to contain only genotypes

locus <- Mydata[, -c(1,2,3,4,16:3086)] # We remove the extra columns and we keep only 20 SNP (to make calculation faster) 
```

could be:

****

To convert MydataR to genind object (adegent): Mydata2 needs to contain only genotypes. We remove the extra columns and we keep only 20 SNP (to make calculation faster) 

```r
locus <- Mydata[, -c(1,2,3,4,16:3086)]
```

Does this sound reasonable?

**Comment by smanel** [comment]
Yes. 
I will do it.

**Comment by zkamvar** [comment]
I'm sorry for taking so long to get to this! Thank you for being so patient, @smanel.

**Pull request merged**
