### PR TITLE
update TEMPLATE

### LINKED ISSUE #186: Add Research Question to TEMPLATE
Suggested by Reviewer 2:

> I would also add “Research question” before the “Introduction” part. Indeed, the introduction should explain the steps necessary to meet the scientific question. The main scientific question should really be emphasized from the beginning because this is central to the design of the research (see [Benestan et al 2016](http://onlinelibrary.wiley.com/doi/10.1111/mec.13647/full)).

### LINKED ISSUE #187: Add Visualizing the results to TEMPLATE vignette
From Reviewer 2:

> I would add a section “Visualizing the results” into the “Analysis” part. Indeed, they are often many ways to visualize the same summary statistics. Therefore, having this section will help researcher to check quickly if the tutorial produce the results they want to get, without going further into the code language, or even improving the code by adding a new way to present such results.

### PR DESCRIPTION
**Pull request by zkamvar**
This fixes #186 and fixes #187.

I've additionally added a couple of more chunks to show that echo and eval are true by default.

### CODE REVIEW

**Comment by hlapp** [comment]
Looks great to me. Can @smanel or @mmlopezu take a look too and signal agreement that this completes addressing the reviewer comments in #186 and #187?

**Comment by mmlopezu** [comment]
@zkamvar 

I think these modifications address comments from the reviewer. I personally think these great additions! Should we suggest these changes for all existing vignettes? Or only new ones?

**Comment by hlapp** [comment]
I don't want to cut off the discussion - it can continue here regardless - but I'm going to merge this given @mmlopezu approval.

**Comment by zkamvar** [comment]
I think it might be prudent to suggest changes to the existing vignettes.

**Pull request merged**
