### PR TITLE
Add directory for images

### PR DESCRIPTION
**Pull request by zkamvar**

### CODE REVIEW

**Comment by zkamvar** [comment]
@hlapp, you cool with this?

**Comment by hlapp** [comment]
Yes, but we'll also need a change to `build/Makefile` to actually copy the folder, right?

**Comment by zkamvar** [comment]
Good catch!

**Comment by zkamvar** [comment]
Aaaand it looks like you'll have to manually merge it if the changes are okay.

**Comment by hlapp** [comment]
There is no action taken on the `IMAGEDIR` though. 

I think I understand now why simply mirroring `DATADIR` will actually _not_ work. We don't copy the `data/` directory to the published website - the contents of the directory are only needed to compile the .Rmd files, and by leaving the directory where it is and flattening the directory tree of vignettes from the repo root to to everything under `build/` maintains the same relative position between vignettes and data files.

This is different for the `images/` directory, and maintaining the relative position is _not_ possible _iff_ its content is to be referenced from files in the repo root and from vignettes in subdirectories. If it is only for images references from files in the repo root, then the links are maintained by copying the whole folder to `build/`.

**Comment by zkamvar** [comment]
I probably should close this and just make it a branch on this account, then.

**Comment by hlapp** [comment]
Is it reasonable though to expect at least for now that static images will only be used from files in the repo root? That seems key for whether the simple solution in implementation here will work, or whether we need to think through this deeper.

The problem itself seems somewhat tangential to me to the publication milestone, even if it will likely come back in the future. So I'd rather kick that can down the road in the interest of focusing on polishing the vignettes we have.

**Comment by zkamvar** [comment]
I agree that this could be dealt with later. I'll go ahead and close this pull request since there are merge conflicts and add the images directory on another branch.

**Pull request closed without merging**
