### PR TITLE
Add weekly build

### PR DESCRIPTION
**Pull request by zkamvar**
This will build and deploy the website on a weekly basis every Tuesday at 07:00 UTC. It is temporarily set to allow this branch so that we can confirm it works before merging.

### CODE REVIEW

**Comment by zkamvar** [comment]
Note: once merged, this will fix #205

**Comment by zkamvar** [comment]
And we're getting circleci errors:

```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
ssh: no key found
```

**Comment by hlapp** [comment]
> Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.

I think we can ignore this. At least I have.

> ssh: no key found

Hmm. Do you need to re-authorize CircleCI for your account, or add an ssh key of your own?

Perhaps what really needs to be done is to create a machine user as per recommendations, and then have the deployment (`git push` to gh-pages branch) use that machine user.

**Comment by hlapp** [comment]
Apparently this has been failing for nearly a year with (strangely, because other builds still went past that) an SSH key missing error.

Also, I didn't seem to have received notifications about the failures.

I think I fixed both now. For notifications, I suppose one needs to change _notify only for branches I've pushed to_ to _notify about all builds_ for this repo.

**Pull request merged**
