### PR TITLE
.md file with links to other resources

### PR DESCRIPTION
**Pull request by mmlopezu**
First draft of this page with existing resources for R and Github basics

### CODE REVIEW

**Comment by zkamvar** [comment]
I've changed the name of the file and added an item in the dropdown menu. I notice that this has some overlap with GETTINGSTARTED.md. Should we merge these two?

**Comment by mmlopezu** [comment]
Sure, that make sense. I think the 'Getting started page' would benefit
from text. Short descriptions explaining what the websites have...

On Tue, May 12, 2015 at 1:25 PM, Zhian N. Kamvar <notifications@github.com>
wrote:

> I've changed the name of the file and added an item in the dropdown menu.
> I notice that this has some overlap with GETTINGSTARTED.md. Should we merge
> these two?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/pull/45#issuecomment-101357734>.
>



-- 
Margarita M. López-Uribe
Postdoctoral Researcher
Department of Entomology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by zkamvar** [comment]
On second thought, I think I'm going to add a new tab to the menu bar that will say "Resources"

**Comment by zkamvar** [comment]
Heres what it looks like thusfar:
image

**Comment by mmlopezu** [comment]
Cool!

**Comment by smanel** [comment]
Super!

**Comment by hlapp** [comment]
I guess I would put that file in the root folder, where all the other such "meta" documentation files are. But we can do that after merging, and the link in the menu doesn't change because of it.

**Pull request merged**
