### PR TITLE
Manel new

### PR DESCRIPTION
**Pull request by smanel**
New vignette SNP: individual genetic distance.

### CODE REVIEW

**Comment by zkamvar** [comment]
I have removed `eval = FALSE` from most of the code chunks and added in the chunk that would read in the data set. 

When looking at the output, I noticed that `dist.gene` gives a maximum distance of 3 loci out of 100, whereas `diss.dist` gives an average of 40:

image

I think this has something to do with the amount of missing data, because when I tabulate the missing data per locus, I get 98 loci with at least one sample missing:

```r
missing_data <- info_table(Mydata1, type = "missing")
sum(missing_data["Total", 1:100] > 0)
## [1] 98
barplot(missing_data["Total", 1:100], xlab = "Locus", ylab = "Percent Missing")
```

image

We could possibly use this to caution users to inspect the default parameters like `pairwise.deletion = FALSE` and understand the consequences. What do you think?

**Comment by smanel** [comment]
Yes I agree with your suggestion and I will do the modifications.

**Comment by hlapp** [comment]
@zkamvar have you had a chance to check again? Ready to merge?

**Comment by zkamvar** [comment]
@hlapp, I was under the impression that @smanel was not yet finished as indicated by [line 151: "still to do"](https://github.com/NESCent/popgenInfo/blame/af3f6bf8f4cb3a4e218e04e4ce3341ef1cdcdac5/use/VignetteIndvidualGeneticDistancesSNP.Rmd#L150-L151). Regarding the modifications previously suggested, they have been addressed. 

I think we should include a phrase in the CONTRIBUTING file that says that the contributor should indicate when the vignette is ready to merge by adding a comment saying "ready to merge" or something similar. But that is another issue.

**Comment by hlapp** [comment]
> I think we should include a phrase in the CONTRIBUTING file that says that the contributor should indicate when the vignette is ready to merge by adding a comment saying "ready to merge" or something similar.

That's a good idea!

**Comment by zkamvar** [comment]
I will create the link in the dropdown menu and merge it.

**Comment by zkamvar** [comment]
I have made some small modifications to the document style-wise, but the essence is still there. If @smanel is okay with my modifications, I will merge.

**Comment by smanel** [comment]
I am OK.

**Pull request merged**
