### PR TITLE
Add images directory

### PR DESCRIPTION
**Pull request by zkamvar**
This additionally adds figure 1 for the paper. The SVG file falls under MIT, but does the image require a CC-BY?

### CODE REVIEW

**Comment by zkamvar** [comment]
@hlapp, Do you have any input?

**Comment by hlapp** [comment]
I was going to look at it in more detail. Re: licenses, IMHO there's no reason not to apply CC-BY to all images regardless of their format, and it looks like the SVG as it's written has the namespace ([xmlns:cc="http://creativecommons.org/ns#](https://github.com/NESCent/popgenInfo/blob/add-images/images/workflow.svg?short_path=c69b8f1#L6)) and means ([<metadata/>](https://github.com/NESCent/popgenInfo/blob/add-images/images/workflow.svg?short_path=c69b8f1#L154-L165)) already predefined for asserting the license right within the file itself; the tool that writes it (Inkscape?) just needs to be told the appropriate value to put there.

**Comment by zkamvar** [comment]
ping

**Comment by zkamvar** [comment]
@hlapp, would you be okay merging this? IMO, it should be merged before we submit the paper so that it has precedence regarding the license.

**Comment by hlapp** [comment]
Sorry I somehow missed the fact that you had added fixes and mistakenly thought that I had to tweak something here. This looks perfect. I'm going ahead to merge. Sorry for the delay, and great fix to the SVG!

**Comment by zkamvar** [comment]
> Sorry for the delay

No worries, it makes me feel like I've accomplished something! :joy_cat:

**Pull request merged**
