### PR TITLE
Dataselection

### PR DESCRIPTION
**Pull request by smanel**
A new vignette to detect the signal of selection.

### CODE REVIEW

**Comment by hlapp** [comment]
@smanel I don't know how you branched, but this is not from an old version of the master branch, which is why it is failing. Perhaps you need to update your local clone?

**Comment by hlapp** [comment]
Hi @smanel - I'm going to close this. The branch is very old (9 months), and uses a file for a vignette that has meanwhile been renamed, see #100. Can you update your local clone, and branch off then?

**Comment by hlapp** [comment]
We also now have two branches which seemingly differ only in capitalization and appear otherwise identical, `Dataselection` and `dataselection`. I'm inclined to delete both - we seem to have the vignette in the repo, and the branching off point of these is just way too old to be useful in any way.

@zkamvar could you cast a second pair of eyes on this and either approve or disapprove deleting those branches?

**Comment by zkamvar** [comment]
Looking at both of these branches, they are identical without any new content. What's more is that they revert commits. These branches should be deleted.

**Pull request closed without merging**
