### PR TITLE
Fix baseline build errors

### PR DESCRIPTION
**Pull request by hlapp**
This merges #79 and #85 which together (but not individually) should fix the baseline build errors we've been struggling with due to CRAN package changes.

### CODE REVIEW

**Comment by hlapp** [comment]
OK we've got the next error that hasn't been seen before:

```R
Quitting from lines 67-75 (StartSNP.Rmd) 
Error in eval(expr, envir, enclos) : 
  no slot of name "loc.nall" for this object of class "genind"
```
How do we fix this? @smanel (attributed author of `StartSNP.Rmd`) or @zkamvar, any suggestions?

**Comment by zkamvar** [comment]
[Line 72](https://github.com/NESCent/popgenInfo/blame/fix-build-errors/use/StartSNP.Rmd#L72) is the culprit here.

```diff
- Mydata1@loc.nall
+ nAll(Mydata1)
```

**Comment by zkamvar** [comment]
I'll fix it here and see if that works

**Comment by hlapp** [comment]
That did work, and now we have the next error:
```R
Quitting from lines 67-75 (StartSNP.Rmd) 
Error in genind2hierfstat(Mydata1) : 
  alleles must be encoded as integers or nucleotides. Exiting
```
How did we fix this before?

**Comment by zkamvar** [comment]
I just noticed that there are some issues with data sanitization (adegenet can't handle "." in locus names). I'm going to work on this a little and see if I can produce a fix.

**Comment by zkamvar** [comment]
I found the problem. It exists within hierfstat.

**Comment by hlapp** [comment]
> I found the problem. It exists within hierfstat.

So `hierfstat` needs to be fixed and then we switch the container build to installing hierfstat from Github again?

**Comment by zkamvar** [comment]
> So hierfstat needs to be fixed and then we switch the container build to installing hierfstat from Github again?

I think that's about the size of it :frowning:

**Comment by zkamvar** [comment]
Although, it might pass if we included 12 loci in the data.

**Comment by hlapp** [comment]
> Although, it might pass if we included 12 loci in the data.

Nope, it didn't.

**Comment by zkamvar** [comment]
actually, it *did*, but now another error is reeling its ugly head:

```
Quitting from lines 75-78 (SummarySequenceData.Rmd) 
Error in validObject(x) : invalid class "genind" object: FALSE
Calls: <Anonymous> ... summary -> summary -> .local -> is.genind -> validObject
```

This one is caused by the fact that Margarita updated her data for PopDiffSequenceData. @mmlopezu, Did you double the number of samples in your data?

**Comment by zkamvar** [comment]
After looking into it, there are many things that are going to fail in that vignette because it was one of the first ones written back when adegenet still had HWE.test.genind. 

I think the main things that need to be removed are the Fst and HW tests, since they require diploids.

Additionally, when adegenet 2.0.1 comes down the line, the names for the summary object will be different -_-

**Comment by hlapp** [comment]
So perhaps the solution is to remove that vignette here, and to reintroduce it on a development branch, where it can wait until it is fixed. I can do that if that would work for everyone.

**Comment by smanel** [comment]
Good idea!

**Comment by zkamvar** [comment]
> So perhaps the solution is to remove that vignette here, and to reintroduce it on a development branch, where it can wait until it is fixed. I can do that if that would work for everyone.

I think that works. @mmlopezu, does that work for you?

**Comment by hlapp** [comment]
That does the trick indeed. I'll merge to master and resolve the conflict.

**Comment by mmlopezu** [comment]
@zkamvar <https://github.com/zkamvar> yes, it does work. I'll work on it
this weekend.

On Wed, Dec 16, 2015 at 4:35 PM, Zhian N. Kamvar <notifications@github.com>
wrote:

> So perhaps the solution is to remove that vignette here, and to
> reintroduce it on a development branch, where it can wait until it is
> fixed. I can do that if that would work for everyone.
>
> I think that works. @mmlopezu <https://github.com/mmlopezu>, does that
> work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/pull/87#issuecomment-165247161>.
>



-- 
Margarita M. López-Uribe
NSF Postdoctoral Fellow
Department of Entomology
and
Department of Applied Ecology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by hlapp** [comment]
@mmlopezu - note that this pull request is now merged, so please update your fork and create a new branch when you resume work on it.

**Comment by mmlopezu** [comment]
@hlapp - will do

On Thu, Dec 17, 2015 at 9:56 PM, Hilmar Lapp <notifications@github.com>
wrote:

> @mmlopezu <https://github.com/mmlopezu> - note that this pull request is
> now merged, so please update your fork and create a new branch when you
> resume work on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/pull/87#issuecomment-165655582>.
>



-- 
Margarita M. López-Uribe
NSF Postdoctoral Fellow
Department of Entomology
and
Department of Applied Ecology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Pull request merged**
